### ISSUE TITLE
Intro - Word Choice

### ISSUE THREAD

**Issue by anjakefala** [lazywithclass/project-lamp#3]
From Intro: "Functional Programming (FP) can be thought of as a method of writing computer programs where *specification*"

Referring to "specification" without additional information to what kind of specification is confusing! I didn't understand what you meant by this.

**Comment by lazywithclass** [comment]
@damedebugger what would you suggest instead?

@IvantheTricourne what do you think about this? I don't have a problem with it.

**Comment by lazywithclass** [comment]
Cleared with @damedebugger
